```{r}
library(tigris)
library(terra)
library(sf)
library(sp)
library(tidyverse)
options(tigris_use_cache = TRUE)
```

```{r}
for(fip in c(17, 18, 26, 39, 55)) {
  tracts = tigris::tracts(fip, cb = T, year = 2021)
  if(fip == 17) {
    all_tracts = tracts
  } else {
    all_tracts = rbind(all_tracts, tracts)
  }
}

counties = tigris::counties(state = c(17, 18, 26, 39, 55), cb = T, year = 2021)
```


```{r}
# tracts_sf = st_as_sf(all_tracts)
counties_sf = st_as_sf(counties)
counties_sf = st_boundary(st_union(counties_sf))
counties_sf = st_transform(counties_sf, "EPSG:3857")
# 
st_write(counties_sf, "./data/study_area.shp", append = F)

```


```{r}
library(ggplot2)
library(ggmap)
study_area.map = ggplot() +
  geom_sf(data = counties_sf) + 
    theme_bw(base_size = 10) +
    theme(
      panel.grid = element_blank(),
      axis.title = element_text(size = 10),
      axis.text  = element_text(size = 8),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 9),
      plot.title = element_text(size = 11, hjust = 0.5)
    )
ggsave("./plots/study_area.png", 
       study_area.map,
       width = 6,
      height = 4,
      dpi = 300,
      units = "in")
```



```{r}


```